### ISSUE TITLE
pathSet and pathGet in store

### ISSUE THREAD

**Issue by adriaanwm** [staydecent/atom#20]
Not sure where to post this request, maybe pwa-starter or elements would be better.

In some side projects I've been using a store with `get` and `set` functions that I find very useful. With wasmuth naming it would be `path` and `pathSet` I think. Anyways it looks like this.

`store.get([])` returns entire state
`store.get(['nested', 'value'])` get nested value
`store.set(['nested', 'value'], newValue)` sets nested value

I also added a `store.setBatch` which is used like
```
store.setBatch(
    [['nested', 'value'], newValue],
    [['nested', 'somewhereElse'], another value],
)
```

**Comment by staydecent** [comment]
We've had the path-reducer in pwa-starter for awhile now. I recently removed it as a default, since most people just use setState, but it can always be installed: https://github.com/staydecent/wasmuth/blob/master/packages/node_modules/%40wasmuth/path-reducer/path-reducer.js

Also, atom has supported batching of actions since Jun 15, 2017!

```
dispatch(
  pathSet('nested.value', newValue),
  pathSet('nested.somewhereElse', anotherValue),
)
```

☝️ Is nearly identical syntax to your example, no? I'm not too keen on hiding the dispatch API, as long-lived projects are better off [refactoring](https://staydecent.ca/code/why-redux-over-global-basic-store/) to specific actions/reducers eventually, rather than just generic setters.

Could add a small wrapper function in pwa-starter, like `storeGet`?

```
export function storeGet (path) {
  return W.path(path)(store.getState())
}
```

**Comment by adriaanwm** [comment]
Ah nice, `pathSet` is what I was missing! Thanks! I remember using that extensively in Purposely
`storeGet` would be handy might use that in alpha.

**Comment by staydecent** [comment]
@adriaanwm Would you prefer we include pathReducer by default in pwa? Totally open to that.

**Comment by adriaanwm** [comment]
@staydecent definitely
