### ISSUE TITLE
Middle ware and combine multiple stores?

### ISSUE THREAD

**Issue by magnumjs** [staydecent/atom#4]
I like this simple clear implementation, would be great to add ability for middle ware and combining multiple stores or would that be reducers?

**Comment by staydecent** [comment]
For combining reducers I usually just merge the resulting objects from multiple function calls. So, I would pass a single main reducer to atom, which then calls any number of other reducers that focus on a certain subsection of actions:

```javascript
function reducer (action, state) {
  return Object.assign(state, profileReducer(action, state), todosReducer(action, state), ...)
}
```

The issue is if you dispatch an action that results in an async operation (returning a function rather than a state object). Though, in this case we could use a simple helper:

```javascript
function combineReducers (fns, action, state) {
  let newState = {}
  fns.forEach((fn) => {
    let result = fn(action, state)
    // if not a function, merge with new state
    if (!result.hasOwnProperty('arguments')) {
      newState = Object.assign(newState, result)
    }
  })
  return newState
}
```

I suppose I could add a `combineReducers` type function to atom. 

EDIT: Actually, perhaps the first param of the `atom` function could accept a function or an array of functions, and in the latter case, wrap them in a `combineReducers` type function like I posted above.

That seems nice, yeah?
